version: "3.3"
services:
  youtube_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: vitalplay/youtube_bot:latest
    env_file:
      - .env
    container_name: youtube_bot
    restart: always
    volumes:
      - ${HOME}/youtube:/app/youtube
